---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/getenvoy --version
    register: getenvoy_test_output
  - name: getenvoy --version
    debug:
      msg: '{{ getenvoy_test_output.stdout }}'
