---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install in {{ getenvoy_install_dir }}
  become: yes
  stat:
    path: '{{ getenvoy_install_dir }}'
  register: getenvoy_binary
- when: not getenvoy_binary.stat.exists
  block:
    - name: downloading {{ getenvoy_url }} to {{ getenvoy_tmp_tgz }}
      become: yes
      become_user: root
      get_url:
        url: '{{ getenvoy_url }}'
        dest: '{{ getenvoy_tmp_tgz }}'
        mode: 0644
        checksum: '{{ getenvoy_checksum }}'
    - name: mkdir {{ getenvoy_install_dir }}
      become: yes
      become_user: root
      file:
        path: '{{ getenvoy_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ getenvoy_tmp_tgz }} into {{ getenvoy_install_dir }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ getenvoy_tmp_tgz }}'
        dest: '{{ getenvoy_install_dir }}'
        creates: '{{ getenvoy_install_exe }}'
  always:
    - name: rm {{ getenvoy_tmp_tgz }}
      become: yes
      become_user: root
      file:
        path: '{{ getenvoy_tmp_tgz }}'
        state: absent
- name: linking {{ getenvoy_link_exe }} to {{ getenvoy_install_exe }}
  become: yes
  become_user: root
  file:
    src: '{{ getenvoy_install_exe }}'
    dest: '{{ getenvoy_link_exe }}'
    state: link

- name: mkdir {{ getenvoy_home_dir }}
  become: yes
  become_user: root
  file:
    path: '{{ getenvoy_home_dir }}'
    state: directory
    mode: 0755

- name: installing envoy proxy distributions...
  when: getenvoy_install is defined
  become: yes
  become_user: root
  with_items: '{{ getenvoy_install }}'
  command: '{{ getenvoy_link_exe }} --home-dir {{ getenvoy_home_dir }} use {{ item.version }}'
  args:
    creates: '{{ getenvoy_home_dir }}/versions/{{ item.version }}/bin/envoy'

- name: linking envoy...
  when: getenvoy_link is defined
  become: yes
  become_user: root
  file:
    src: '{{ getenvoy_home_dir }}/versions/{{ getenvoy_link.version }}/bin/envoy'
    dest: '{{ getenvoy_parent_install_dir }}/bin/envoy'
    state: link
